### PR TITLE
FIX(3iD): Update FAQ copy

### LINKED ISSUE #707: FEAT(onboarding): Update FAQ Copy
# Why

The onboarding dashboard FAQ helps users understand 3ID so that they can use it and earn invitations.

# What

Please update the FAQ copy so that it is more reflective of features and goals.

# How

> Please design, decompose, and discuss: break the logical **What** into a set of issues documenting physical implementation tasks.

- [ ] Issue #1
- [ ] Issue #2
- [ ] Issue #3

# Notes

- [User journey](https://www.notion.so/kubelt/3iD-Onboarding-18fd37f9dec340178dbe86d48afd2431).
- [Design assets](https://www.figma.com/file/EqUEbCGHGnZXDMSUbrxhX7/Kubelt?node-id=2540%3A10207).

### PR DESCRIPTION
**Pull request by Cosmin-Parvulescu**
# Description

Updated 3iD onboarding copy

Closes #707 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Asymptotically

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: 3iD/src/screens/onboarding/Onboard.tsx [hunk 1]
```diff
@@ -496,31 +498,53 @@ export default function Onboard({ navigation }: { navigation: any }) {
...
+                    marginVertical: "1em",
                   }}
-                  source={require("../../assets/dropdown.png")}
-                ></Image>
+                >
+                  Now that you've claimed your 3iD, developers can now query
+                  {" "}<a href={`https://threeid.xyz/${account}`}>your profile URL</a> to fetch your public profile information and
+                  avatar. You'll also able to share your profile on social media
+                  to share your NFT collections.
+                </Text>
```
Comment (maurerbot) [inline 3iD/src/screens/onboarding/Onboard.tsx:544]: Now that you've claimed your **3ID**,  other applications can query your [profile]() to fetch your public profile details including your avatar.  You can also use https://threeid.xyz/....  to promote your profile and NFTs on social media.

Comment (maurerbot) [reply 3iD/src/screens/onboarding/Onboard.tsx:544]: later we can list a bunch of apps that support this

cc @alfl

File: 3iD/src/screens/onboarding/Onboard.tsx [hunk 2]
```diff
@@ -533,31 +560,47 @@ export default function Onboard({ navigation }: { navigation: any }) {
...
+                    marginTop: "1em",
                   }}
-                  source={require("../../assets/dropdown.png")}
-                ></Image>
+                >
+                  Next we will be focusing on storage, account linking, and
+                  messaging but we're really interested in what you think we
+                  should be working on too. Join us on Discord and Twitter to
+                  keep up to date and tell us what we should do next.
+                </Text>
```
Comment (maurerbot) [inline 3iD/src/screens/onboarding/Onboard.tsx:603]: Next we will be focusing on storage, account linking, and messaging but we're also interested in what **you** think we should be working on! Join us on Discord and Twitter to share your idea  and keep up to date with the Kubelt team.

Comment (maurerbot) [reply 3iD/src/screens/onboarding/Onboard.tsx:603]: Also link to Twitter and Discord

File: 3iD/src/screens/onboarding/Onboard.tsx [hunk 3]
```diff
@@ -570,31 +613,45 @@ export default function Onboard({ navigation }: { navigation: any }) {
...
+                <Text
                   style={{
-                    width: 14,
-                    height: 7,
+                    marginTop: "1em",
                   }}
-                  source={require("../../assets/dropdown.png")}
-                ></Image>
+                >
+                  Yes. You can list your invite card on Open Sea or transfer it
```
Comment (maurerbot) [inline 3iD/src/screens/onboarding/Onboard.tsx:652]: links to collections on open sea

File: 3iD/src/screens/onboarding/Onboard.tsx [hunk 4]
```diff
@@ -607,31 +664,51 @@ export default function Onboard({ navigation }: { navigation: any }) {
...
+                >
+                  Your gradient PFP is a soul bound avatar made up of 4 color
+                  traits -- one version color and three more colors traits
+                  selected from a pool of common, uncommon, rare, and epic
+                  colors. The first color trait probability is based on which
+                  popular NFTs you currently hold. The second color trait is
+                  based on which of our developer collections you hold. The last
+                  color trait is based on you ETH balance. Click here to read
+                  the code.
+                </Text>
```
Comment (maurerbot) [inline 3iD/src/screens/onboarding/Onboard.tsx:711]: Your 3ID gradient PFP is a soul bound avatar made up of 4 color traits -- one version color and three common, uncommon, rare and epic colors traits. Rarity is decided by several factors.
1. The first color trait probability is based on which popular NFTs you currently hold. 
2. The second color trait is based on which of our developer collections you hold. 
3. The last color trait is based on you ETH balance. 

Click here to read the code. Once generated, your 3ID gradient PFP is soul bound to your identity. More generations of this PFP will be released corresponding with every major version of 3ID.

File: 3iD/src/screens/onboarding/Onboard.tsx [hunk 5]
```diff
@@ -644,31 +721,50 @@ export default function Onboard({ navigation }: { navigation: any }) {
...
-                ></Image>
+                >
+                  3iD was created by Kubelt, a decentralized application
+                  platform and is inspired by the digital identity
+                  specification. Users like yourself who claim their 3iD will
+                  also be able to permission applications to access data,
+                  messages and more. Our goal is to eliminate email as a basis
+                  of online identity and shift the norm towards being
+                  user-centric and decentralized.
+                </Text>
```
Comment (maurerbot) [inline 3iD/src/screens/onboarding/Onboard.tsx:767]: 3ID was created by [Kubelt](https://kubelt.com), a decentralized application platform and is inspired by Web3 and the digital identity specification. Instead of applications centralizing user data, 3ID users like yourself will be able to permission/revoke applications to access personal data, messages and more. Our goal is to eliminate email as a basis of online identity and shift the norm towards being cryptographic, user-centric and decentralized platforms.

File: 3iD/src/screens/onboarding/Onboard.tsx (hunk 4 above)
Comment (maurerbot) [reply 3iD/src/screens/onboarding/Onboard.tsx:711]: add link to github nftar

**Review by maurerbot — CHANGES_REQUESTED** [review]

**Review by maurerbot — APPROVED** [review]
