### PR TITLE
fix(passport): Authn & Authz screen icon, name and cleanup

### LINKED ISSUE #1498: feat(passport): show App's logo from Console in authorization page
When a client_id is provided in passport (retrieved from CONSOLE_PARAMS cookie), ensure the logo of the app corresponding to that client ID is shown in the auth page.

### PR DESCRIPTION
**Pull request by betimshahini**
# Description

Cleans up authorization screen, param checks, app name, etc.

- Closes #1498

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- By temporarily enabling setting of scopes in Console, setting some scopes on a couple of apps, and then hitting the `/authenticate` endpoint in passport with `client_id` and other query params.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation website
- [ ] I have made corresponding changes to the literal docs
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: apps/passport/app/routes/authorize/index.tsx [hunk 1]
```diff
@@ -17,13 +17,20 @@ import { Profile } from '@kubelt/galaxy-client'
...
 
   if (clientId) {
     if (!state) throw json({ message: 'state is required' }, 400)
     if (!redirectUri) throw json({ message: 'redirect_uri is required' }, 400)
-    if (!scope || !Array.isArray(scope) || scope.length === 0) {
+    try {
+      new URL(redirectUri)
+    } catch {
+      throw json(
+        { message: 'valid URI is required in redirect_uri param' },
```
Comment (maurerbot) [inline apps/passport/app/routes/authorize/index.tsx:29]: 👍

**Review by maurerbot — APPROVED** [review]
