### PR TITLE
bug(threeid): profile ens auth match

### LINKED ISSUE #1174: bug(threeid): profile ens auth match
## What is the current behavior?

ENS names don't know I'm logged in

## What is the expected behavior?

Going to my profile with ens name should show that I'm logged in

### PR DESCRIPTION
**Pull request by Cosmin-Parvulescu**
# Description

Added ENS -> address resolution for the public profile parameter

- Closes #1174 

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Flowing

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation website
- [ ] I have made corresponding changes to the literal docs
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: apps/threeid/app/routes/$profile.tsx [hunk 1]
```diff
@@ -46,7 +46,11 @@ export const loader: LoaderFunction = async (args) => {
   const session = await getUserSession(request)
   const jwt = session.get('jwt')
 
-  let targetAddress = params.profile
+  if (!params.profile) throw new Error('Profile is required')
```
Comment (maurerbot) [inline apps/threeid/app/routes/$profile.tsx:49]: this would never happen because the route gates it.

**Review by maurerbot — CHANGES_REQUESTED** [review]

**Review by maurerbot — APPROVED** [review]
