### PR TITLE
fix(nftar): NFTar Speedup Attempts

### LINKED ISSUE #1264: chore(nftar): Speed pt1: add CF images to voucher for web and keep ipfs for token
- [ ] store pfp in CF and add cfPfp prop in voucher 
- [ ] store cover in CF and cfCover prop in voucher
- [ ] use cfPfp and cfPFP to generate OF preview image (nftar og image endpoint)

Notes:
- cfPfp and cfCover prop might not be needed if CID can be used in CF images

### PR DESCRIPTION
**Pull request by alfl**
# Description

Speedup attempts for NFTar OG tag generation.

- Closes #1264

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Local, goerli

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [na] I have made corresponding changes to the documentation website
- [na] I have made corresponding changes to the literal docs
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: projects/nftar/src/app.js [hunk 1]
```diff
@@ -306,116 +308,22 @@ jsonrpc.method('3id_genPFP', async (ctx, next) => {
     console.log(`Crypto took ${t1 - t0} milliseconds.`);
 
     // Generate the response to send to the client.
-    ctx.body = {
-      metadata: metadata.data,
-      voucher,
-      signature,
+    const body = {
+        metadata: metadata.data,
+        voucher,
```
Comment (maurerbot) [inline projects/nftar/src/app.js:313]: @alfl if voucher has the cf images as props too we can use that in the bffs

**Review by maurerbot — COMMENTED** [review]
dirty solution is now just add cf props to the voucher and we make the associated changes in bff to use that as profile image and cover while bootstrapping an account

**Comment by alfl** [comment]
> dirty solution is now just add cf props to the voucher and we make the associated changes in bff to use that as profile image and cover while bootstrapping an account
> 
> Let's land this tomorrow please

This doesn't work. I have it implemented locally -- CF Images has bad performance issues for a process like this. Looking at R2.

**Comment by alfl** [comment]
> hm. it's slow to finalize the url? no fire and forget model?

IPFS is 20-30 seconds, CF Images is 10-15 seconds. The cover and PFP uploads have to finish before OG generation. So fire-and-forget hides the race condition but then you have to make sure you wait until they're done before doing OG.

Makes more sense IMO to just generate the OG when you know the uploads are done, but now you're baking in these delays.

Quick Google shows performance is a known issue with CF Images -- it's for simple web use cases.

R2 might be faster and give us some advantages in serving the OGs straight from the public public.

**Comment by alfl** [comment]
> if doing r2 create a "content" worker in /services ...

web3 CMS, yes 😂 

There was a feature request about image sharing on Farcaster -- might be able to help dwr out :)

**Comment by alfl** [comment]
Still doing some smoke tests but speeds much improved:

- Moved image storage to R2, but preserved the `ipfs://` URLs embedded in the NFT metadata
- Parallelized some requests and generally made things async fire-and-forget calls.
- Reducing PFP image size gave us ~3x-5x speedup, reduced network traffic delays, and container memory consumption.

There is more juice to squeeze in moving R2 to a custom domain, which lifts some of Cloudflare's rate limits.

**Comment by alfl** [comment]
Also updated URLs and removed invite code paths. More cleanup possible too.

**Review by szkl — APPROVED** [review]
