### PR TITLE
feat(passport): Microsoft login integration and fixes

### LINKED ISSUE #1362: Microsoft 365

### PR DESCRIPTION
**Pull request by betimshahini**
# Description

Adds Microsoft login integration:
- [x] OAuth login
- [x] Retrieval and caching of profile image
- [x] Fixes and cleanup in Passport 

- Closes #1362 

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Comprehensively :/

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation website
- [ ] I have made corresponding changes to the literal docs
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: apps/passport/app/routes/authenticate/microsoft/callback.ts [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+  const hash = keccak256(encoder.encode(idref))
+  const address = (AddressURNSpace.urn(hash) +
+    `?+node_type=${NodeType.OAuth}&addr_type=${OAuthAddressType.Microsoft}`) as AddressURN
+  const addressClient = getAddressClient(address)
+  const account = await addressClient.resolveAccount.query()
+  const existingOAuthData = await addressClient.getOAuthData.query()
+  if (
+    !existingOAuthData ||
+    !existingOAuthData.profile ||
+    existingOAuthData?.profile?.provider !== OAuthAddressType.Microsoft
```
[the remark this answers is not in the document]
Comment (szkl) [reply apps/passport/app/routes/authenticate/microsoft/callback.ts:40]: Though, I think the condition should be based on the data path `profile._json.picture` here. If stored image URL differs from the one in the authentication result.

File: apps/passport/app/routes/authenticate/microsoft/callback.ts [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+    )
+    profile._json.threeidImageUrl = imageUrl
+
+    await addressClient.setOAuthData.mutate(authRes)
+  }
+
+  return authenticateAddress(address, account)
+}
+
+const cacheImageFromMSGraph = async (
```
Comment (szkl) [inline apps/passport/app/routes/authenticate/microsoft/callback.ts:56]: It looks like a reusable utility function that optionally accepts request headers.

File: apps/passport/app/routes/authenticate/microsoft/callback.ts [hunk 3]
```diff
@@ -0,0 +1,93 @@
...
+    !existingOAuthData.profile ||
+    existingOAuthData?.profile?.provider !== OAuthAddressType.Microsoft
+  ) {
+    //If we don't already have a microsoft oauth data set, we cache
+    //the image and set the OAuth data set for the address
+    const imageUrl = await cacheImageFromMSGraph(
+      profile._json.picture,
+      authRes.accessToken
+    )
+    profile._json.threeidImageUrl = imageUrl
```
Comment (szkl) [inline apps/passport/app/routes/authenticate/microsoft/callback.ts:48]: I'm not against changing the structure of a third-party entity but I'd prefer to set own generated data in an internal structure.

File: apps/passport/app/routes/authorize/index.tsx [hunk 4]
```diff
@@ -110,14 +123,28 @@ export const loader: LoaderFunction = async ({ request, context }) => {
...
+              }
+              case OAuthAddressType.Microsoft: {
+                const microsoftProfile = res as OAuthMicrosoftProfile
+                const gradient = await generateGradient(
+                  microsoftProfile.sub.toString()
+                )
+                return {
+                  displayName: microsoftProfile.name,
+                  pfp: {
+                    //Cached profile image
```
Comment (szkl) [inline apps/passport/app/routes/authorize/index.tsx:135]: Just curious how the comment helps in this context. I wouldn't think it would be worth it.

File: apps/passport/app/utils/gradient.server.ts [hunk 5]
```diff
@@ -1,14 +1,17 @@
...
     cf: {
       cacheEverything: true,
       cacheTtl: 86400,
       cacheKey: gradientSeed,
     },
   })
-    .then((res) => res.text())
+    .then((res) => {
+      return res.text()
+    })
```
Comment (szkl) [inline apps/passport/app/utils/gradient.server.ts:11]: You had your chance to replace `then`s and `catch`s 😄

**Review by szkl — CHANGES_REQUESTED** [review]

File: apps/passport/app/routes/authenticate/microsoft/callback.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (szkl) [reply apps/passport/app/routes/authenticate/microsoft/callback.ts:40]: I suggest

```typescript
existingOAuthData?.profile == null
```

File: apps/passport/app/routes/authenticate/microsoft/callback.ts (hunk 3 above)
Comment (szkl) [reply apps/passport/app/routes/authenticate/microsoft/callback.ts:48]: I think address nodes can store data in the storage as needed. I'm not sure if the data getter/setter methods are available for all node types yet, though.

Comment (szkl) [reply apps/passport/app/routes/authenticate/microsoft/callback.ts:48]: > Yeah, that concern is why I "namespaced" it.

Practically not a concern, hence why I'm not against it but it changes the schema of an external data structure. It could fail validation. Again, not an important case for this instance. I just like discussing such stuff.

**Review by szkl — APPROVED** [review]
